from tuple_lib import *
tuple1 = (1,0,0)
tuple2 = (2,2,2)
tuple3 = (1,2,3)
scalar = 5
#print(add(tuple1,tuple2))
#print(sub(tuple1,tuple2))
#print(mult(tuple3,tuple2))
#print(div(tuple1,tuple2))
#print(addScalar(scalar,tuple3))
#print(subScalar(scalar,tuple3))
#print(multScalar(scalar,tuple3))
#print(divScalar(scalar,tuple1))
#print(mag(tuple1))
#print(unit(tuple2))
#print(dot(tuple1,tuple2))
#print(cross(tuple1,tuple2))
#print(projScalar(tuple1,tuple2))
#print(proj(tuple1,tuple2))